// next/vristo-next-main/pages/elements/treeview.tsx
import Link from 'next/link';
import CodeHighlight from '../../components/Highlight';
import { useEffect, useState } from 'react';
import AnimateHeight from 'react-animate-height';
import { setPageTitle } from '../../store/themeConfigSlice';
import { useDispatch } from 'react-redux';
import IconCode from '@/components/Icon/IconCode';
import IconCaretDown from '@/components/Icon/IconCaretDown';
import IconFolder from '@/components/Icon/IconFolder';
import IconTxtFile from '@/components/Icon/IconTxtFile';
import IconFolderPlus from '@/components/Icon/IconFolderPlus';
import IconFolderMinus from '@/components/Icon/IconFolderMinus';
const Treeview = () => {
    const dispatch = useDispatch();
    useEffect(() => {
        dispatch(setPageTitle('Treeview'));
    });
    const [codeArr, setCodeArr] = useState<string[]>([]);

    const toggleCode = (name: string) => {
        if (codeArr.includes(name)) {
            setCodeArr((value) => value.filter((d) => d !== name));
        } else {
            setCodeArr([...codeArr, name]);
        }
    };

    const [treeview1, setTreeview1] = useState<string[]>(['images']);
    const [pagesSubMenu, setPagesSubMenu] = useState(false);

    const toggleTreeview1 = (name: any) => {
        if (treeview1.includes(name)) {
            setTreeview1((value) => value.filter((d) => d !== name));
        } else {
            setTreeview1([...treeview1, name]);
        }
    };

    const [treeview2, setTreeview2] = useState<string[]>(['parent']);

    const toggleTreeview2 = (name: any) => {
        if (treeview2.includes(name)) {
            setTreeview2((value) => value.filter((d) => d !== name));
        } else {
            setTreeview2([...treeview2, name]);
        }
    };

    return (
        <div>
            <ul className="flex space-x-2 rtl:space-x-reverse">
                <li>
                    <Link href="#" className="text-primary hover:underline">
                        Elements
                    </Link>
                </li>
                <li className="before:content-['/'] ltr:before:mr-2 rtl:before:ml-2">
                    <span>Treeview</span>
                </li>
            </ul>
            <div className="grid grid-cols-1 gap-6 pt-5 lg:grid-cols-2">
                {/* Animated */}
                <div className="panel">
                    <div className="mb-5 flex items-center justify-between">
                        <h5 className="text-lg font-semibold dark:text-white-light">Animated</h5>
                        <button
                            onClick={() => {
                                toggleCode('code1');
                            }}
                            className="font-semibold hover:text-gray-400 dark:text-gray-400 dark:hover:text-gray-600"
                        >
                            <span className="flex items-center">
                                <IconCode className="me-2" />
                                Code
                            </span>
                        </button>
                    </div>
                    <div className="mb-5">
                        <ul className="font-semibold">
                            <li className="py-[5px]">
                                <button type="button" className={`${treeview1.includes('css') ? 'active' : ''}`} onClick={() => toggleTreeview1('css')}>
                                    <IconCaretDown className={`w-5 h-5 text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2 ${treeview1.includes('css') && 'rotate-180'}`} />
                                    <IconFolder className="text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2" />
                                    CSS
                                </button>
                                <AnimateHeight duration={300} height={treeview1.includes('css') ? 'auto' : 0}>
                                    <ul className="ltr:pl-14 rtl:pr-14">
                                        <li className="py-[5px]">
                                            <IconTxtFile className="w-4.5 h-4.5 text-primary inline ltr:mr-2 rtl:ml-2" />
                                            style.css
                                        </li>
                                    </ul>
                                </AnimateHeight>
                            </li>
                            <li className="py-[5px]">
                                <button type="button" className={`${treeview1.includes('images') ? 'active' : ''}`} onClick={() => toggleTreeview1('images')}>
                                    <IconCaretDown className={`w-5 h-5 text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2 ${treeview1.includes('images') && 'rotate-180'}`} />
                                    <IconFolder className="text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2" />
                                    Images
                                </button>
                                <AnimateHeight duration={300} height={treeview1.includes('images') ? 'auto' : 0}>
                                    <ul className="ltr:pl-14 rtl:pr-14">
                                        <li className="py-[5px]">
                                            <IconTxtFile className="w-4.5 h-4.5 text-primary inline ltr:mr-2 rtl:ml-2" />
                                            profile-16.jpeg
                                        </li>
                                        <li className="py-[5px]">
                                            <IconTxtFile className="w-4.5 h-4.5 text-primary inline ltr:mr-2 rtl:ml-2" />
                                            background.png
                                        </li>
                                        <li className="py-[5px]">
                                            <IconTxtFile className="w-4.5 h-4.5 text-primary inline ltr:mr-2 rtl:ml-2" />
                                            gallery.jpg
                                        </li>
                                    </ul>
                                </AnimateHeight>
                            </li>
                            <li className="py-[5px]">
                                <button type="button" className={`${treeview1.includes('html') ? 'active' : ''}`} onClick={() => toggleTreeview1('html')}>
                                    <IconCaretDown className={`w-5 h-5 text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2 ${treeview1.includes('html') && 'rotate-180'}`} />
                                    <IconFolder className="text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2" />
                                    HTML
                                </button>
                                <AnimateHeight duration={300} height={treeview1.includes('html') ? 'auto' : 0}>
                                    <ul className="ltr:pl-14 rtl:pr-14">
                                        <li className="py-[5px]">
                                            <button type="button" className={`${pagesSubMenu ? 'open' : ''} `} onClick={() => setPagesSubMenu(!pagesSubMenu)}>
                                                <IconCaretDown className={`w-5 h-5 text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2 ${treeview1.includes('pages') && 'rotate-180'}`} />
                                                <IconFolder className="text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2" />
                                                PAGES
                                            </button>
                                            <AnimateHeight duration={300} height={pagesSubMenu ? 'auto' : 0}>
                                                <ul className="ltr:pl-14 rtl:pr-14">
                                                    <li className="py-[5px]">
                                                        <IconTxtFile className="w-4.5 h-4.5 text-primary inline ltr:mr-2 rtl:ml-2" />
                                                        file name
                                                    </li>
                                                    <li className="py-[5px]">
                                                        <IconTxtFile className="w-4.5 h-4.5 text-primary inline ltr:mr-2 rtl:ml-2" />
                                                        file name
                                                    </li>
                                                    <li className="py-[5px]">
                                                        <IconTxtFile className="w-4.5 h-4.5 text-primary inline ltr:mr-2 rtl:ml-2" />
                                                        file name
                                                    </li>
                                                </ul>
                                            </AnimateHeight>
                                        </li>
                                        <li className="py-[5px] ltr:pl-8 rtl:pr-8">
                                            <IconTxtFile className="w-4.5 h-4.5 text-primary inline ltr:mr-2 rtl:ml-2" />
                                            file name
                                        </li>
                                        <li className="py-[5px] ltr:pl-8 rtl:pr-8">
                                            <IconTxtFile className="w-4.5 h-4.5 text-primary inline ltr:mr-2 rtl:ml-2" />
                                            file name
                                        </li>
                                    </ul>
                                </AnimateHeight>
                            </li>
                            <li className="py-[5px] ltr:pl-7 rtl:pr-7">
                                <IconTxtFile className="w-4.5 h-4.5 text-primary inline ltr:mr-2 rtl:ml-2" />
                                index.html
                            </li>
                            <li className="py-[5px] ltr:pl-7 rtl:pr-7">
                                <IconTxtFile className="w-4.5 h-4.5 text-primary inline ltr:mr-2 rtl:ml-2" />
                                components.html
                            </li>
                        </ul>
                    </div>
                    {codeArr.includes('code1') && (
                        <CodeHighlight>
                            <pre className="language-typescript">
                                {`import { useState } from 'react';
import AnimateHeight from 'react-animate-height';

const [treeview1, setTreeview1] = useState<string[]>(['images']);
const [pagesSubMenu, setPagesSubMenu] = useState(false);

const toggleTreeview1 = (name: any) => {
    if (treeview1.includes(name)) {
        setTreeview1((value) => value.filter((d) => d !== name));
    } else {
        setTreeview1([...treeview1, name]);
    }
};

<ul className="font-semibold">
    <li className="py-[5px]">
        <button type="button" className={\`${treeview1.includes('css') ? 'active' : ''}\`} onClick={() => toggleTreeview1('css')}>
            <svg>...</svg>
            <svg>...</svg>
            CSS
        </button>
        <AnimateHeight duration={300} height={treeview1.includes('css') ? 'auto' : 0}>
            <ul className="ltr:pl-14 rtl:pr-14">
                <li className="py-[5px]">
                    <svg>...</svg>
                    style.css
                </li>
            </ul>
        </AnimateHeight>
    </li>
    <li className="py-[5px]">
        <button type="button" className={\`${treeview1.includes('images') ? 'active' : ''}\`} onClick={() => toggleTreeview1('images')}>
            <svg>...</svg>
            <svg>...</svg>
            Images
        </button>
        <AnimateHeight duration={300} height={treeview1.includes('images') ? 'auto' : 0}>
            <ul className="ltr:pl-14 rtl:pr-14">
                <li className="py-[5px]">
                    <svg>...</svg>
                    profile-16.jpeg
                </li>
                <li className="py-[5px]">
                    <svg>...</svg>
                    background.png
                </li>
                <li className="py-[5px]">
                    <svg>...</svg>
                    gallery.jpg
                </li>
            </ul>
        </AnimateHeight>
    </li>
    <li className="py-[5px]">
        <button type="button" className={\`${treeview1.includes('html') ? 'active' : ''}\`} onClick={() => toggleTreeview1('html')}>
            <svg>...</svg>
            <svg>...</svg>
            HTML
        </button>
        <AnimateHeight duration={300} height={treeview1.includes('html') ? 'auto' : 0}>
            <ul className="ltr:pl-14 rtl:pr-14">
                <li className="py-[5px]">
                    <button type="button" className={\`${pagesSubMenu ? 'open' : ''}\`} onClick={() => setPagesSubMenu(!pagesSubMenu)}>
                        <svg>...</svg>
                        <svg>...</svg>
                        PAGES
                    </button>
                    <AnimateHeight duration={300} height={pagesSubMenu ? 'auto' : 0}>
                        <ul className="ltr:pl-14 rtl:pr-14">
                            <li className="py-[5px]">
                                <svg>...</svg>
                                file name
                            </li>
                            <li className="py-[5px]">
                                <svg>...</svg>
                                file name
                            </li>
                            <li className="py-[5px]">
                                <svg>...</svg>
                                file name
                            </li>
                        </ul>
                    </AnimateHeight>
                </li>
                <li className="py-[5px] ltr:pl-8 rtl:pr-8">
                    <svg>...</svg>
                    file name
                </li>
                <li className="py-[5px] ltr:pl-8 rtl:pr-8">
                    <svg>...</svg>
                    file name
                </li>
            </ul>
        </AnimateHeight>
    </li>
    <li className="py-[5px] ltr:pl-7 rtl:pr-7">
        <svg>...</svg>
        index.html
    </li>
    <li className="py-[5px] ltr:pl-7 rtl:pr-7">
        <svg>...</svg>
        components.html
    </li>
</ul>`}</pre>
                        </CodeHighlight>
                    )}
                </div>
                {/* Basic */}
                <div className="panel">
                    <div className="mb-5 flex items-center justify-between">
                        <h5 className="text-lg font-semibold dark:text-white-light">Basic</h5>
                        <button
                            onClick={() => {
                                toggleCode('code2');
                            }}
                            className="font-semibold hover:text-gray-400 dark:text-gray-400 dark:hover:text-gray-600"
                        >
                            <span className="flex items-center">
                                <IconCode className="me-2" />
                                Code
                            </span>
                        </button>
                    </div>
                    <div className="mb-5">
                        <ul className="font-semibold">
                            <li>
                                <button type="button" className={`${treeview2.includes('parent') ? 'active' : ''}`} onClick={() => toggleTreeview2('parent')}>
                                    {treeview2.includes('parent') ? (
                                        <IconFolderPlus className="text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2" />
                                    ) : (
                                        <IconFolderMinus className="text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2" />
                                    )}
                                    Parent Node
                                </button>
                                <AnimateHeight duration={300} height={treeview2.includes('parent') ? 'auto' : 0} easing="none">
                                    <ul>
                                        <li className="py-[5px] ltr:pl-7 rtl:pr-7">
                                            <button type="button" className={`${treeview2.includes('img') ? 'open' : ''} `} onClick={() => toggleTreeview2('img')}>
                                                {treeview2.includes('img') ? (
                                                    <IconFolderPlus className="text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2" />
                                                ) : (
                                                    <IconFolderMinus className="text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2" />
                                                )}
                                                img
                                            </button>
                                            <ul></ul>
                                        </li>
                                        <li className="py-[5px] ltr:pl-7 rtl:pr-7">
                                            <button type="button" className={`${treeview2.includes('css') ? 'open' : ''} `} onClick={() => toggleTreeview2('css')}>
                                                {treeview2.includes('css') ? (
                                                    <IconFolderPlus className="text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2" />
                                                ) : (
                                                    <IconFolderMinus className="text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2" />
                                                )}
                                                css
                                            </button>
                                            <AnimateHeight duration={300} height={treeview2.includes('css') ? 'auto' : 0} easing="none">
                                                <ul>
                                                    <li className="py-[5px] text-secondary ltr:pl-7 rtl:pr-7">style.css</li>
                                                </ul>
                                            </AnimateHeight>
                                        </li>
                                        <li className="py-[5px] ltr:pl-7 rtl:pr-7">
                                            <button type="button" className={`${treeview2.includes('js') ? 'open' : ''} `} onClick={() => toggleTreeview2('js')}>
                                                {treeview2.includes('js') ? (
                                                    <IconFolderPlus className="text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2" />
                                                ) : (
                                                    <IconFolderMinus className="text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2" />
                                                )}
                                                js
                                            </button>
                                            <AnimateHeight duration={300} height={treeview2.includes('js') ? 'auto' : 0} easing="none">
                                                <ul>
                                                    <li className="py-[5px] text-secondary ltr:pl-7 rtl:pr-7">script.js</li>
                                                </ul>
                                            </AnimateHeight>
                                        </li>
                                        <li className="py-[5px] text-secondary ltr:pl-7 rtl:pr-7">index.html</li>
                                    </ul>
                                </AnimateHeight>
                            </li>
                        </ul>
                    </div>
                    {codeArr.includes('code2') && (
                        <CodeHighlight>
                            <pre className="language-typescript">
                                {`import { useState } from 'react';
import AnimateHeight from 'react-animate-height';

const [pagesSubMenu, setPagesSubMenu] = useState(false);

const [treeview2, setTreeview2] = useState<string[]>(['parent']);

const toggleTreeview2 = (name: any) => {
    if (treeview2.includes(name)) {
        setTreeview2((value) => value.filter((d) => d !== name));
    } else {
        setTreeview2([...treeview2, name]);
    }
};

<ul className="font-semibold">
    <li>
        <button type="button" className={\`${treeview2.includes('parent') ? 'active' : ''}\`} onClick={() => toggleTreeview2('parent')}>
            {treeview2.includes('parent') ? (
                <svg>...</svg>
            ) : (
                <svg>...</svg>
            )}
            Parent Node
        </button>
        <AnimateHeight duration={300} height={treeview2.includes('parent') ? 'auto' : 0} easing="none">
            <ul>
                <li className="py-[5px] ltr:pl-7 rtl:pr-7">
                    <button type="button" className={\`${treeview2.includes('img') ? 'open' : ''}\`} onClick={() => toggleTreeview2('img')}>
                        {treeview2.includes('img') ? (
                            <svg>...</svg>
                        ) : (
                            <svg>...</svg>
                        )}
                        img
                    </button>
                    <ul></ul>
                </li>
                <li className="py-[5px] ltr:pl-7 rtl:pr-7">
                    <button type="button" className={\`${treeview2.includes('css') ? 'open' : ''}\`} onClick={() => toggleTreeview2('css')}>
                        {treeview2.includes('css') ? (
                            <svg>...</svg>
                        ) : (
                            <svg>...</svg>
                        )}
                        css
                    </button>
                    <AnimateHeight duration={300} height={treeview2.includes('css') ? 'auto' : 0} easing="none">
                        <ul>
                            <li className="py-[5px] ltr:pl-7 rtl:pr-7 text-secondary">style.css</li>
                        </ul>
                    </AnimateHeight>
                </li>
                <li className="py-[5px] ltr:pl-7 rtl:pr-7">
                    <button type="button" className={\`${treeview2.includes('js') ? 'open' : ''}\`} onClick={() => toggleTreeview2('js')}>
                        {treeview2.includes('js') ? (
                            <svg>...</svg>
                        ) : (
                            <svg>...</svg>
                        )}
                        js
                    </button>
                    <AnimateHeight duration={300} height={treeview2.includes('js') ? 'auto' : 0} easing="none">
                        <ul>
                            <li className="py-[5px] ltr:pl-7 rtl:pr-7 text-secondary">script.js</li>
                        </ul>
                    </AnimateHeight>
                </li>
                <li className="py-[5px] ltr:pl-7 rtl:pr-7 text-secondary">index.html</li>
            </ul>
        </AnimateHeight>
    </li>
</ul>`}</pre>
                        </CodeHighlight>
                    )}
                </div>
            </div>
        </div>
    );
};

export default Treeview;

// nuxt/vristo-nuxt-main/pages/elements/treeview.vue
<template>
    <div>
        <ul class="flex space-x-2 rtl:space-x-reverse">
            <li>
                <a href="javascript:;" class="text-primary hover:underline">Elements</a>
            </li>
            <li class="before:content-['/'] ltr:before:mr-2 rtl:before:ml-2">
                <span>Treeview</span>
            </li>
        </ul>
        <div class="grid grid-cols-1 gap-6 pt-5 lg:grid-cols-2">
            <div class="panel">
                <div class="mb-5 flex items-center justify-between">
                    <h5 class="text-lg font-semibold dark:text-white-light">Animated</h5>
                    <a class="font-semibold hover:text-gray-400 dark:text-gray-400 dark:hover:text-gray-600" href="javascript:;" @click="toggleCode('code1')"
                        ><span class="flex items-center">
                            <icon-code class="me-2" />
                            Code
                        </span></a
                    >
                </div>
                <div class="mb-5">
                    <ul class="font-semibold">
                        <li class="py-[5px]">
                            <button type="button" @click="toggleTreeview1('css')">
                                <icon-caret-down
                                    class="w-5 h-5 text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2"
                                    :class="{ 'rotate-180': treeview1.includes('css') }"
                                />
                                <icon-folder class="text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2" />
                                CSS
                            </button>
                            <vue-collapsible :isOpen="treeview1.includes('css')">
                                <ul class="ltr:pl-14 rtl:pr-14">
                                    <li class="py-[5px]">
                                        <icon-txt-file class="w-4.5 h-4.5 text-primary inline ltr:mr-2 rtl:ml-2" />
                                        style.css
                                    </li>
                                </ul>
                            </vue-collapsible>
                        </li>
                        <li class="py-[5px]">
                            <button type="button" @click="toggleTreeview1('images')">
                                <icon-caret-down
                                    class="w-5 h-5 text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2"
                                    :class="{ 'rotate-180': treeview1.includes('images') }"
                                />
                                <icon-folder class="text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2" />
                                Images
                            </button>
                            <vue-collapsible :isOpen="treeview1.includes('images')">
                                <ul class="ltr:pl-14 rtl:pr-14">
                                    <li class="py-[5px]">
                                        <icon-txt-file class="w-4.5 h-4.5 text-primary inline ltr:mr-2 rtl:ml-2" />
                                        profile-16.jpeg
                                    </li>
                                    <li class="py-[5px]">
                                        <icon-txt-file class="w-4.5 h-4.5 text-primary inline ltr:mr-2 rtl:ml-2" />
                                        background.png
                                    </li>
                                    <li class="py-[5px]">
                                        <icon-txt-file class="w-4.5 h-4.5 text-primary inline ltr:mr-2 rtl:ml-2" />
                                        gallery.jpg
                                    </li>
                                </ul>
                            </vue-collapsible>
                        </li>
                        <li class="py-[5px]">
                            <button type="button" @click="toggleTreeview1('html')">
                                <icon-caret-down
                                    class="w-5 h-5 text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2"
                                    :class="{ 'rotate-180': treeview1.includes('html') }"
                                />
                                <icon-folder class="text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2" />
                                HTML
                            </button>
                            <vue-collapsible :isOpen="treeview1.includes('html')">
                                <ul class="ltr:pl-14 rtl:pr-14">
                                    <li class="py-[5px]">
                                        <button type="button" @click="toggleTreeview1('pages')">
                                            <icon-caret-down
                                                class="w-5 h-5 text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2"
                                                :class="{ 'rotate-180': treeview1.includes('pages') }"
                                            />
                                            <icon-folder class="text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2" />
                                            PAGES
                                        </button>
                                        <vue-collapsible :isOpen="treeview1.includes('pages')">
                                            <ul class="ltr:pl-14 rtl:pr-14">
                                                <li class="py-[5px]">
                                                    <icon-txt-file class="w-4.5 h-4.5 text-primary inline ltr:mr-2 rtl:ml-2" />
                                                    file name
                                                </li>
                                                <li class="py-[5px]">
                                                    <icon-txt-file class="w-4.5 h-4.5 text-primary inline ltr:mr-2 rtl:ml-2" />
                                                    file name
                                                </li>
                                                <li class="py-[5px]">
                                                    <icon-txt-file class="w-4.5 h-4.5 text-primary inline ltr:mr-2 rtl:ml-2" />
                                                    file name
                                                </li>
                                            </ul>
                                        </vue-collapsible>
                                    </li>
                                    <li class="py-[5px] ltr:pl-8 rtl:pr-8">
                                        <icon-txt-file class="w-4.5 h-4.5 text-primary inline ltr:mr-2 rtl:ml-2" />
                                        file name
                                    </li>
                                    <li class="py-[5px] ltr:pl-8 rtl:pr-8">
                                        <icon-txt-file class="w-4.5 h-4.5 text-primary inline ltr:mr-2 rtl:ml-2" />
                                        file name
                                    </li>
                                </ul>
                            </vue-collapsible>
                        </li>
                        <li class="py-[5px] ltr:pl-7 rtl:pr-7">
                            <icon-txt-file class="w-4.5 h-4.5 text-primary inline ltr:mr-2 rtl:ml-2" />
                            index.html
                        </li>
                        <li class="py-[5px] ltr:pl-7 rtl:pr-7">
                            <icon-txt-file class="w-4.5 h-4.5 text-primary inline ltr:mr-2 rtl:ml-2" />
                            components.html
                        </li>
                    </ul>
                </div>
                <template v-if="codeArr.includes('code1')">
                    <highlight>
                        <pre>
&lt;!-- animated --&gt;
&lt;ul class=&quot;font-semibold&quot;&gt;
  &lt;li class=&quot;py-[5px]&quot;&gt;
    &lt;button type=&quot;button&quot; @click=&quot;toggleTreeview1('css')&quot;&gt;
      &lt;svg&gt; ... &lt;/svg&gt;
      CSS
    &lt;/button&gt;
    &lt;vue-collapsible :isOpen=&quot;treeview1.includes('css')&quot;&gt;
      &lt;ul class=&quot;ltr:pl-14 rtl:pr-14&quot;&gt;
        &lt;li class=&quot;py-[5px]&quot;&gt;
          &lt;svg&gt; ... &lt;/svg&gt;
          style.css
        &lt;/li&gt;
      &lt;/ul&gt;
    &lt;/vue-collapsible&gt;
  &lt;/li&gt;
  &lt;li class=&quot;py-[5px]&quot;&gt;
    &lt;button type=&quot;button&quot; @click=&quot;toggleTreeview1('images')&quot;&gt;
      &lt;svg&gt; ... &lt;/svg&gt;
      Images
    &lt;/button&gt;
    &lt;vue-collapsible :isOpen=&quot;treeview1.includes('images')&quot;&gt;
      &lt;ul class=&quot;ltr:pl-14 rtl:pr-14&quot;&gt;
        &lt;li class=&quot;py-[5px]&quot;&gt;
          &lt;svg&gt; ... &lt;/svg&gt;
          profile-16.jpeg
        &lt;/li&gt;
        &lt;li class=&quot;py-[5px]&quot;&gt;&lt;svg&gt; ... &lt;/svg&gt;background.png&lt;/li&gt;
        &lt;li class=&quot;py-[5px]&quot;&gt;&lt;svg&gt; ... &lt;/svg&gt;gallery.jpg&lt;/li&gt;
      &lt;/ul&gt;
    &lt;/vue-collapsible&gt;
  &lt;/li&gt;
  &lt;li class=&quot;py-[5px]&quot;&gt;
    &lt;button type=&quot;button&quot; @click=&quot;toggleTreeview1('html')&quot;&gt;
      &lt;svg&gt; ... &lt;/svg&gt;
      HTML
    &lt;/button&gt;
    &lt;vue-collapsible :isOpen=&quot;treeview1.includes('html')&quot;&gt;
      &lt;ul class=&quot;ltr:pl-14 rtl:pr-14&quot;&gt;
        &lt;li class=&quot;py-[5px]&quot;&gt;
          &lt;button type=&quot;button&quot; @click=&quot;toggleTreeview1('pages')&quot;&gt;
            &lt;svg&gt; ... &lt;/svg&gt;
            PAGES
          &lt;/button&gt;
          &lt;vue-collapsible :isOpen=&quot;treeview1.includes('pages')&quot;&gt;
            &lt;ul class=&quot;ltr:pl-14 rtl:pr-14&quot;&gt;
              &lt;li class=&quot;py-[5px]&quot;&gt;
                &lt;svg&gt; ... &lt;/svg&gt;
                file name
              &lt;/li&gt;
              &lt;li class=&quot;py-[5px]&quot;&gt;
                &lt;svg&gt; ... &lt;/svg&gt;
                file name
              &lt;/li&gt;
              &lt;li class=&quot;py-[5px]&quot;&gt;
                &lt;svg&gt; ... &lt;/svg&gt;
                file name
              &lt;/li&gt;
            &lt;/ul&gt;
          &lt;/vue-collapsible&gt;
        &lt;/li&gt;
        &lt;li class=&quot;py-[5px] ltr:pl-8 rtl:pr-8&quot;&gt;&lt;svg&gt; ... &lt;/svg&gt;file name&lt;/li&gt;
        &lt;li class=&quot;py-[5px] ltr:pl-8 rtl:pr-8&quot;&gt;&lt;svg&gt; ... &lt;/svg&gt;file name&lt;/li&gt;
      &lt;/ul&gt;
    &lt;/vue-collapsible&gt;
  &lt;/li&gt;
  &lt;li class=&quot;py-[5px] ltr:pl-7 rtl:pr-7&quot;&gt;&lt;svg&gt; ... &lt;/svg&gt;index.html&lt;/li&gt;
  &lt;li class=&quot;py-[5px] ltr:pl-7 rtl:pr-7&quot;&gt;&lt;svg&gt; ... &lt;/svg&gt;components.html&lt;/li&gt;
&lt;/ul&gt;

&lt;!-- script --&gt;
&lt;script lang=&quot;ts&quot; setup&gt;
  import { ref } from 'vue';
  import VueCollapsible from 'vue-height-collapsible/vue3';
  const treeview1: any = ref([]);
  const toggleTreeview1 = (name: string) =&gt; {
    if (treeview1.value.includes(name as never)) {
      treeview1.value = treeview1.value.filter((d) =&gt; d != name);
    } else {
      treeview1.value.push(name as never);
    }
  };
&lt;/script&gt;
</pre
                        >
                    </highlight>
                </template>
            </div>

            <div class="panel">
                <div class="mb-5 flex items-center justify-between">
                    <h5 class="text-lg font-semibold dark:text-white-light">Basic</h5>
                    <a class="font-semibold hover:text-gray-400 dark:text-gray-400 dark:hover:text-gray-600" href="javascript:;" @click="toggleCode('code2')"
                        ><span class="flex items-center">
                            <icon-code class="me-2" />
                            Code
                        </span></a
                    >
                </div>
                <div class="mb-5">
                    <ul class="no-animtion font-semibold">
                        <li>
                            <button type="button" @click="toggleTreeview2('parent-node')">
                                <icon-folder-plus v-if="treeview2.includes('parent-node')" class="text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2" />
                                <icon-folder-minus v-else class="text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2" />
                                Parent Node
                            </button>
                            <vue-collapsible :isOpen="treeview2.includes('parent-node')">
                                <ul>
                                    <li class="py-[5px] ltr:pl-7 rtl:pr-7">
                                        <button type="button" @click="toggleTreeview2('img')">
                                            <icon-folder-plus v-if="treeview2.includes('img')" class="text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2" />
                                            <icon-folder-minus v-else class="text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2" />
                                            img
                                        </button>
                                        <vue-collapsible :isOpen="treeview2.includes('img')">
                                            <ul></ul>
                                        </vue-collapsible>
                                    </li>
                                    <li class="py-[5px] ltr:pl-7 rtl:pr-7">
                                        <button type="button" @click="toggleTreeview2('css')">
                                            <icon-folder-plus v-if="treeview2.includes('css')" class="text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2" />
                                            <icon-folder-minus v-else class="text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2" />
                                            css
                                        </button>
                                        <vue-collapsible :isOpen="treeview2.includes('css')">
                                            <ul>
                                                <li class="py-[5px] text-secondary ltr:pl-7 rtl:pr-7">style.css</li>
                                            </ul>
                                        </vue-collapsible>
                                    </li>
                                    <li class="py-[5px] ltr:pl-7 rtl:pr-7">
                                        <button type="button" @click="toggleTreeview2('js')">
                                            <icon-folder-plus v-if="treeview2.includes('js')" class="text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2" />
                                            <icon-folder-minus v-else class="text-primary inline relative -top-1 ltr:mr-2 rtl:ml-2" />
                                            js
                                        </button>
                                        <vue-collapsible :isOpen="treeview2.includes('js')">
                                            <ul>
                                                <li class="py-[5px] text-secondary ltr:pl-7 rtl:pr-7">script.js</li>
                                            </ul>
                                        </vue-collapsible>
                                    </li>
                                    <li class="py-[5px] text-secondary ltr:pl-7 rtl:pr-7">index.html</li>
                                </ul>
                            </vue-collapsible>
                        </li>
                    </ul>
                </div>
                <template v-if="codeArr.includes('code2')">
                    <highlight>
                        <pre>
&lt;!-- basic --&gt;
&lt;ul class=&quot;font-semibold no-animtion&quot;&gt;
  &lt;li&gt;
    &lt;button type=&quot;button&quot; @click=&quot;toggleTreeview2('parent-node')&quot;&gt;
      &lt;svg&gt; ... &lt;/svg&gt;
      Parent Node
    &lt;/button&gt;
    &lt;vue-collapsible :isOpen=&quot;treeview2.includes('parent-node')&quot;&gt;
      &lt;ul&gt;
        &lt;li class=&quot;py-[5px] ltr:pl-7 rtl:pr-7&quot;&gt;
          &lt;button type=&quot;button&quot; @click=&quot;toggleTreeview2('img')&quot;&gt;
            &lt;svg&gt; ... &lt;/svg&gt;
            img
          &lt;/button&gt;
          &lt;vue-collapsible :isOpen=&quot;treeview2.includes('img')&quot;&gt;
            &lt;ul&gt;&lt;/ul&gt;
          &lt;/vue-collapsible&gt;
        &lt;/li&gt;
        &lt;li class=&quot;py-[5px] ltr:pl-7 rtl:pr-7&quot;&gt;
          &lt;button type=&quot;button&quot; @click=&quot;toggleTreeview2('css')&quot;&gt;
            &lt;svg&gt; ... &lt;/svg&gt;
            css
          &lt;/button&gt;
          &lt;vue-collapsible :isOpen=&quot;treeview2.includes('css')&quot;&gt;
            &lt;ul&gt;
              &lt;li class=&quot;py-[5px] ltr:pl-7 rtl:pr-7 text-secondary&quot;&gt;style.css&lt;/li&gt;
            &lt;/ul&gt;
          &lt;/vue-collapsible&gt;
        &lt;/li&gt;
        &lt;li class=&quot;py-[5px] ltr:pl-7 rtl:pr-7&quot;&gt;
          &lt;button type=&quot;button&quot; @click=&quot;toggleTreeview2('js')&quot;&gt;
            &lt;svg&gt; ... &lt;/svg&gt;
            js
          &lt;/button&gt;
          &lt;vue-collapsible :isOpen=&quot;treeview2.includes('js')&quot;&gt;
            &lt;ul&gt;
              &lt;li class=&quot;py-[5px] ltr:pl-7 rtl:pr-7 text-secondary&quot;&gt;script.js&lt;/li&gt;
            &lt;/ul&gt;
          &lt;/vue-collapsible&gt;
        &lt;/li&gt;
        &lt;li class=&quot;py-[5px] ltr:pl-7 rtl:pr-7 text-secondary&quot;&gt;index.html&lt;/li&gt;
      &lt;/ul&gt;
    &lt;/vue-collapsible&gt;
  &lt;/li&gt;
&lt;/ul&gt;

&lt;!-- script --&gt;
&lt;script lang=&quot;ts&quot; setup&gt;
  import { ref } from 'vue';
  import VueCollapsible from 'vue-height-collapsible/vue3';
  const treeview2: any = ref(['parent-node']);
  const toggleTreeview2 = (name: string) =&gt; {
    if (treeview2.value.includes(name as never)) {
      treeview2.value = treeview2.value.filter((d) =&gt; d != name);
    } else {
      treeview2.value.push(name as never);
    }
  };
&lt;/script&gt;
</pre
                        >
                    </highlight>
                </template>
            </div>
        </div>
    </div>
</template>
<script lang="ts" setup>
    import { ref } from 'vue';
    import highlight from '@/components/plugins/highlight.vue';
    import codePreview from '@/composables/codePreview';
    import VueCollapsible from 'vue-height-collapsible/vue3';
    useHead({ title: 'Treeview' });

    const { codeArr, toggleCode } = codePreview();
    const treeview1: any = ref(['images']);
    const treeview2: any = ref(['parent-node']);

    const toggleTreeview1 = (name: string) => {
        if (treeview1.value.includes(name as never)) {
            treeview1.value = treeview1.value.filter((d: any) => d != name);
        } else {
            treeview1.value.push(name as never);
        }
    };

    const toggleTreeview2 = (name: string) => {
        if (treeview2.value.includes(name as never)) {
            treeview2.value = treeview2.value.filter((d: any) => d != name);
        } else {
            treeview2.value.push(name as never);
        }
    };
</script>
